const ENV = import.meta.env

export default {
  Y_API_KEY: ENV.VITE_Y_API_KEY, 
  OTM_KEY: ENV.VITE_OTM_KEY,
  OTM_PLACES_URL: ENV.VITE_OTM_PLACES_URL,
  OTM_PLACE_URL: ENV.VITE_OTM_PLACE_URL,
  OTM_RADIUS_URL: ENV.VITE_OTM_RADIUS_URL
}
